name: push-workflow1
on: push # 이벤트 종류

jobs:
    push-job:
        runs-on: ubuntu-latest
        steps:
            - name: step1 # name은 생략 가능
              run: echo "hello world"
            - name: step2
              run: | # | 멀티라인 커맨드 사용 하기위해
                  echo "hello world"
                  echo "github action"
