# 이슈가 생성될 때 실행
# 특정 키워드가 포함되면 슬랙으로 공유
# 키워드는 변동사항 생길 수 있음 (추가 , 삭제 등)
# issue event => types: [opend]
name: issue-notity
on:
    issues:
        types: [opened]

jobs:
    get-keyworld:
        runs-on: ubuntu-latest
        outputs:
            level: ${{ steps.get-keyword.outputs.level }}
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: get keyword
              id: get-keyword
              run: |
                  echo level=Undefined >> $GITHUB_OUTPUT

                  keywords=$(cat keyword-list.txt)
                  for keyword in $keywords; do
                   if [[ "${{ github.event.issue.title }}" =~ "$keyword" ]]; then
                    echo level=$keyword >> $GITHUB_OUTPUT
                  fi
                  done
            - name: get output
              run: |
                  echo ${{ steps.get-keyword.outputs.level }}
    slack:
        needs: [get-keyworld]
        if: needs.get-keyworld.outputs.level != 'Undefined'
        runs-on: ubuntu-latest
        #environment: ${{ needs.get-keyworld.outputs.level }} # critical or normal
        strategy:
            matrix:
                environment: ["${{ needs.get-keyworld.outputs.level }}"] # critical or normal  # 매트릭스 사용시 결과는 다르지 않지만  action 타입의 시각적 정보 제공
        environment: ${{ matrix.environment }}
        steps:
            - name: slack
              uses: slackapi/slack-github-action@v1.24.0
              with:
                  payload: |
                      {
                      "attachments" : [
                          {
                            "pretext" : "issue alert message",
                            "color" : "28a745",
                            "fields" : [
                                {
                                  "title" : "Level : ${{ needs.get-keyworld.outputs.level }} ",  
                                  "short" : true,
                                  "value" : "issue url : ${{ github.event.issue.html_url }}"                              
                                }
                              ]
                          }
                        ]
                      }
        env:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL}}
            SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
