name: multiple-event-workflow
on: # 여러개의 이벤트 조건 작성
    push:
    issues:
        types: [opened]
    workflow_dispatch:

jobs:
    multiple_event:
        runs-on: ubuntu-latest
         steps:
            - name: step1 # name은 생략 가능
              run: echo "hello world"
            - name: step2
              run: | # | 멀티라인 커맨드 사용 하기위해
                  echo "hello world"
                  echo "github action"
