# secret 민감한 데이터를 안전하게 저장해서 워크플로우에서 사용 민감 정보를 코드와 분리하여 사용 API key, 암호, 인증 토큰
# 깃헙에서 암호화, 로그에 기록되지 않고, 출력 시 마스킹, 접근제한
name: secret
on: push

jobs:
    get-secrets:
        runs-on: ubuntu-latest
        steps:
            - name: get secrets
              run: echo ${{ secrets.level }}
