#timeout 무한루프 방지를 위한 timeout default 360분
name: timeout
on: push

jobs:
    timeout:
        runs-on: ubuntu-latest
        timeout-minutes: 1 #전체
        steps:
            - name: loop
              run: |
                  count=0
                  while true; do
                    echo "seconds : $count"
                    count=$(( count+1 ))
                    sleep 1
                  done
              timeout-minutes: 1 # setp 단계 time out
            - name: echo
              run: echo hello
